name:                Habits
version:             0.1.0.0
github:              "sironitomas/PD"
license:             GPL3
author:              "Tomas Sironi"
maintainer:          "sironitomas@gmail.com"
copyright:           "2020 Tomas Sironi"

extra-source-files:
- ../README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Habits#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- directory
- text
- time

library:
  source-dirs: src

executables:
  Habits-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Habits

tests:
  Habits-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Habits
